### ISSUE TITLE
FR: Quick Links / Speed Dial

### ISSUE THREAD

**Issue by Gitoffthelawn** [robacarp/photographic_start#6]
Thank you for the wonderful extension!  I can't believe it has so few users right now.  I think part of the reason is that this GitHub repo is not listed on the AMO site, so people may not realize it is open source.  Also, the words "Photographic Start" is missing from the extension's name on AMO, so the current name on AMO looks a bit confusing.

Regardless, I think it's great.  I've been using Tabliss, but it keeps resetting itself (known bug for over a year with no resolution currently in sight), so I've been searching for a replacement.  Your extension looks like a great alternative.

The biggest thing missing from it, for my use, is Quick Links (aka Speed Dial): links on the new tab page that go to user-configurable sites.  Would you be interested in adding that functionality?

Thanks!

**Comment by robacarp** [comment]
@Gitoffthelawn thanks for checking it out. I made photographic_start after similar problems with whatever new-tab-page I was using. Working with AMO is a rather frustrating experience, the website is antiquated and the rules are opaque. I appreciate your suggestions on how to get more attention!

I considered a bunch of features for what to put "on" the new tab page over the pictures but ultimately it's not a feature I would use and so I never built it. I'm a keyboard driver so my hands are always on the keys, any frequently visited site is one or two keys away in the address bar.

I'm certainly open to ideas, but for me the main draw is a new-tab page which just shows me a pretty picture!

**Comment by Gitoffthelawn** [comment]
> @Gitoffthelawn thanks for checking it out.

You bet.  Thanks for making it and putting it on GitHub!

> I made photographic_start after similar problems with whatever new-tab-page I was using.

Interesting that we both had similar experiences.  I just found [[Bonjourr],](https://github.com/victrme/Bonjourr) which is excellent.  The `xpi` is almost 800KB, which is wildly large for such a simple tool, but it's not a total deal-breaker (the *required* geolocation permission might be, but I think/hope that Firefox's settings to disable it will really work).  So far, no settings have been lost with Bonjourr, but I've only had it running a short time.  I wrote a bunch of CSS for Bonjourr to make it look like how I had Tabliss all set up.  I haven't had enough time to play with it to see how/if using more random Unsplash images is possible.

> Working with AMO is a rather frustrating experience, the website is antiquated and the rules are opaque. I appreciate your suggestions on how to get more attention!

You're welcome.  Yes, AMO is definitely, um, well, um, "unique". Just don't get me started about how they change account auth systems all too frequently. ;)

I've seen a [developer named Iglorlogius](https://addons.mozilla.org/firefox/user/13634657/) change the names of some of their extensions on AMO, so it appears to be possible.  Or you can always create an AMO listing with a new extension name if you desire.

> I considered a bunch of features for what to put "on" the new tab page over the pictures but ultimately it's not a feature I would use and so I never built it.

Makes sense! Personally, I like a nice picture plus about a dozen hot links along one edge so as to not obscure the image.  A clock in the lower-right corner is a nice touch, but sometimes it's nice not to know what time it is. :)

> I'm a keyboard driver so my hands are always on the keys, any frequently visited site is one or two keys away in the address bar.

I've often wanted to be a keyboard driver, but find myself reaching for the pointing device quite frequently.  Once manufacturers added wheels to pointing devices, I found them almost indispensable. 

How do you have your web browser set up so that frequently visited sites are only 1 or 2 keys away?  I use bookmark keywords extensively, but those still require 4-8 keystrokes.

> I'm certainly open to ideas, but for me the main draw is a new-tab page which just shows me a pretty picture!

I find the main draw to be the nice pretty pictures too.

Before using Tabliss, I never imagined how much I would appreciate Quick Links.  I always just used keyboard keywords for bookmarks.

I started using Tabliss without any Quick Links, but then I experimented with adding a few.  I was surprised by how often I used them.  Plus, Tabliss has this nice feature that assigns a single keystroke to each Quick Link, so you can just press "1" to open your favourite site, for example.  Even with that nice feature, I found myself clicking on them most of the time.  I think it gave me a few extra moments to enjoy the beautiful photographs.

After I uninstalled Tabliss, I was surprised by how much I missed the Quick Links.

If you choose to add Quick Links functionality, I'm fine with them being as rough as you would like to make them.  IOW, if you just provide a single `textarea` on a barebone settings page in which I can enter some URLS with titles in CSV, XML, JSON, or any other format, that would be totally sufficient.  I can position everything using my own CSS.  Ideally, the extension would have another `textarea` for the custom CSS (like in Tabliss and Bonjourr), but I could just use `userContent.css` to get the job done.

Thanks for your openness, and it's my pleasure to meet you.
